//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1_SubeAdresi
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public short Sehir { get; set; }
        public string PostaKodu { get; set; }
        public string AcikAdres { get; set; }
        public string Semt { get; set; }
        public string PostaKutusu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Faks1 { get; set; }
        public string Mobil { get; set; }
    
        public virtual FirmaGenelBilgi FirmaGenelBilgi { get; set; }
    }
}
