//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1_SirketOrtaklari
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<double> Ortaklik { get; set; }
        public int FirmaID { get; set; }
    
        public virtual FirmaGenelBilgi FirmaGenelBilgi { get; set; }
    }
}
