//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F2_BankaBilgileri
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public string BankaKodu { get; set; }
        public string IbanNo { get; set; }
        public string ParaBirimiKodu { get; set; }
    
        public virtual FirmaGenelBilgi FirmaGenelBilgi { get; set; }
    }
}
