//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F2_FirmaGenelBilgi2
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public int SektorID { get; set; }
        public string FirmaFaliyetSekli { get; set; }
        public string SirketCirosu { get; set; }
        public int SirketCiroYili { get; set; }
        public Nullable<int> ToplamCalisanSayisi { get; set; }
        public Nullable<int> IdariCalisan { get; set; }
        public Nullable<int> Uretim { get; set; }
        public Nullable<int> OnYilFazlaPers { get; set; }
        public Nullable<int> Satis { get; set; }
        public Nullable<int> Kalite { get; set; }
        public bool BagimsizDenetleme { get; set; }
        public bool TedarikciKaliteYonetim { get; set; }
        public bool KaliteSistemiBelgesi { get; set; }
        public string ISO9001_K { get; set; }
        public Nullable<System.DateTime> ISO9001_Sure { get; set; }
        public string ISO14001_K { get; set; }
        public Nullable<System.DateTime> ISO14001_Sure { get; set; }
        public string OHSAS18001_K { get; set; }
        public Nullable<System.DateTime> OHSAS18001_Sure { get; set; }
        public string Diger_K { get; set; }
        public Nullable<System.DateTime> Diger_Sure { get; set; }
    
        public virtual FirmaGenelBilgi FirmaGenelBilgi { get; set; }
    }
}
