//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F3_FirmaGenelBilgi3
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public string FormDolAd { get; set; }
        public string FormDolSoyad { get; set; }
        public string FormDolUnvan { get; set; }
        public string FormDolDepart { get; set; }
        public string FormDolTel { get; set; }
        public string FormDolFaks { get; set; }
    }
}
