//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F3_HariciMal_Tanimlari
    {
        public int ID { get; set; }
        public string HariciMalGrupID { get; set; }
        public string Tanim { get; set; }
        public string Kod { get; set; }
    }
}
