//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F3_SirketCalisanlari
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string CepTel { get; set; }
        public string Email { get; set; }
        public string Dahili { get; set; }
        public string CalisanTipi { get; set; }
    }
}
