//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F3_UrunPortfoyu
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public int HariciMalTanimID { get; set; }
        public byte FaaliyetSekli { get; set; }
    
        public virtual FirmaGenelBilgi FirmaGenelBilgi { get; set; }
    }
}
