//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4_BelgeVeDokuman
    {
        public int ID { get; set; }
        public int FirmaID { get; set; }
        public string SicilTasdik { get; set; }
        public string SicilGazet { get; set; }
        public string İmzaSirkul { get; set; }
        public string TSE { get; set; }
        public string ISO { get; set; }
        public string HizmetYet { get; set; }
        public string Yetki { get; set; }
    }
}
