//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOnKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaGenelBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaGenelBilgi()
        {
            this.F1_FabrikaAdresi = new HashSet<F1_FabrikaAdresi>();
            this.F1_MerkezAdresi = new HashSet<F1_MerkezAdresi>();
            this.F1_SirketOrtaklari = new HashSet<F1_SirketOrtaklari>();
            this.F2_FirmaGenelBilgi2 = new HashSet<F2_FirmaGenelBilgi2>();
            this.F2_Referanslar = new HashSet<F2_Referanslar>();
            this.F1_SubeAdresi = new HashSet<F1_SubeAdresi>();
            this.F2_BankaBilgileri = new HashSet<F2_BankaBilgileri>();
            this.F3_UrunPortfoyu = new HashSet<F3_UrunPortfoyu>();
        }
    
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public byte SirketTuru { get; set; }
        public int KurulusYili { get; set; }
        public bool IliskiliTaraf { get; set; }
        public bool OrtakIliskisi { get; set; }
        public Nullable<int> Sermaye { get; set; }
        public string WebAdresi { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string TCNo { get; set; }
        public Nullable<int> OrtakIliskisiId { get; set; }
        public Nullable<byte> yazismaAdresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F1_FabrikaAdresi> F1_FabrikaAdresi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F1_MerkezAdresi> F1_MerkezAdresi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F1_SirketOrtaklari> F1_SirketOrtaklari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F2_FirmaGenelBilgi2> F2_FirmaGenelBilgi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F2_Referanslar> F2_Referanslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F1_SubeAdresi> F1_SubeAdresi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F2_BankaBilgileri> F2_BankaBilgileri { get; set; }
        public virtual F1_Personeller F1_Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F3_UrunPortfoyu> F3_UrunPortfoyu { get; set; }
    }
}
